package net.zodac.dicefive.device

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.useContents
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import net.zodac.dicefive.platform.Accelerometer
import net.zodac.dicefive.platform.HapticEffect
import net.zodac.dicefive.platform.HapticsPlayer
import net.zodac.dicefive.platform.LicenceReports
import net.zodac.dicefive.platform.PlatformServices
import net.zodac.dicefive.platform.SoundEffect
import net.zodac.dicefive.platform.SoundPlayer
import net.zodac.dicefive.ui.settings.ComposeLicenceDocument
import net.zodac.dicefive.ui.settings.LicenseReport
import net.zodac.dicefive.ui.settings.NoSelectionClearer
import net.zodac.dicefive.ui.settings.SelectionClearer
import platform.AVFAudio.AVAudioPlayer
import platform.CoreMotion.CMMotionManager
import platform.Foundation.NSBundle
import platform.Foundation.NSOperationQueue
import platform.Foundation.NSURL
import platform.UIKit.UIImpactFeedbackGenerator
import platform.UIKit.UIImpactFeedbackStyle

/** Standard gravity: CoreMotion reports acceleration in g, the shared shake detector expects m/s². */
private const val STANDARD_GRAVITY = 9.80665f

/**
 * [PlatformServices] for iOS. Compiled on every build (see app/shared/build.gradle.kts), but not yet run
 * on a device - linking and running needs macOS, and the Xcode project and bundled audio are still
 * to come. See .claude/IOS_SUPPORT.md for what's left.
 */
class IosPlatformServices : PlatformServices {

    private val _transientMessage = MutableStateFlow<String?>(null)

    /** The message [showTransientMessage] last posted, until [TransientMessageHost] has shown it. */
    val transientMessage: StateFlow<String?> = _transientMessage.asStateFlow()

    override fun createSoundPlayer(): SoundPlayer = IosSoundPlayer()

    override fun createHapticsPlayer(): HapticsPlayer = IosHapticsPlayer()

    override fun createAccelerometer(): Accelerometer? = IosAccelerometer().takeIf { it.isAvailable }

    override fun showTransientMessage(message: String) {
        _transientMessage.value = message
    }

    internal fun transientMessageShown() {
        _transientMessage.value = null
    }

    // The licence reports are generated by :app:android's (Android) build; iOS needs its own - an open
    // Phase 5 item in .claude/IOS_SUPPORT.md. Until then, the dialog lists nothing.
    override suspend fun loadLicenceReports(): LicenceReports = LicenceReports.EMPTY

    override fun createSelectionClearer(): SelectionClearer = NoSelectionClearer

    @Composable
    override fun LicenceDocument(report: LicenseReport, modifier: Modifier) = ComposeLicenceDocument(report, modifier)
}

/**
 * One [AVAudioPlayer] per clip, from the app bundle. iOS can't decode the Android build's .ogg clips,
 * so the Xcode project has to bundle AAC copies (`cup_shake.m4a` and so on - see
 * .claude/IOS_SUPPORT.md); a clip that isn't bundled simply stays silent.
 */
@OptIn(ExperimentalForeignApi::class)
private class IosSoundPlayer : SoundPlayer {

    private val players: Map<SoundEffect, AVAudioPlayer> = SoundEffect.entries.mapNotNull { effect ->
        val path = NSBundle.mainBundle.pathForResource(effect.clipName, ofType = "m4a") ?: return@mapNotNull null
        val player = AVAudioPlayer(contentsOfURL = NSURL.fileURLWithPath(path), error = null)
        player.prepareToPlay()
        effect to player
    }.toMap()

    override fun play(effect: SoundEffect, volume: Float) {
        val player = players[effect] ?: return
        player.volume = volume
        player.currentTime = 0.0
        player.play()
    }

    override fun release() {
        players.values.forEach { it.stop() }
    }

    private val SoundEffect.clipName: String
        get() = when (this) {
            SoundEffect.CUP_SHAKE -> "cup_shake"
            SoundEffect.MAT_LANDING -> "mat_landing"
            SoundEffect.HOLD -> "hold"
            SoundEffect.UNHOLD -> "unhold"
            SoundEffect.CELEBRATION -> "celebration"
        }
}

/** UIKit's impact haptics: a light tap for a hold, a firmer one for the cup shake. */
private class IosHapticsPlayer : HapticsPlayer {

    private val holdTick = UIImpactFeedbackGenerator(UIImpactFeedbackStyle.UIImpactFeedbackStyleLight)
    private val shakeBuzz = UIImpactFeedbackGenerator(UIImpactFeedbackStyle.UIImpactFeedbackStyleMedium)

    override fun play(effect: HapticEffect) {
        when (effect) {
            HapticEffect.HOLD_TICK -> holdTick.impactOccurred()
            HapticEffect.SHAKE_BUZZ -> shakeBuzz.impactOccurred()
        }
    }
}

/**
 * CoreMotion's accelerometer, delivered on the main queue and converted from g to m/s² - and negated,
 * since CoreMotion reports gravity itself (face up reads z = -1 g) where [Accelerometer] wants its
 * reaction, as Android does. Its axes are the device's natural portrait ones: not yet turned for a
 * rotated interface (see .claude/IOS_SUPPORT.md).
 */
@OptIn(ExperimentalForeignApi::class)
private class IosAccelerometer : Accelerometer {

    private val motionManager = CMMotionManager()

    val isAvailable: Boolean get() = motionManager.isAccelerometerAvailable()

    override fun start(samplesPerSecond: Int, onSample: (x: Float, y: Float, z: Float) -> Unit) {
        setSamplesPerSecond(samplesPerSecond)
        motionManager.startAccelerometerUpdatesToQueue(NSOperationQueue.mainQueue) { data, _ ->
            data?.acceleration?.useContents {
                onSample(-x.toFloat() * STANDARD_GRAVITY, -y.toFloat() * STANDARD_GRAVITY, -z.toFloat() * STANDARD_GRAVITY)
            }
        }
    }

    // CoreMotion takes a new interval while updates are running.
    override fun setSamplesPerSecond(samplesPerSecond: Int) {
        motionManager.accelerometerUpdateInterval = 1.0 / samplesPerSecond
    }

    override fun stop() {
        motionManager.stopAccelerometerUpdates()
    }
}
