package net.zodac.dicefive.ui.game.style

import androidx.compose.foundation.Image
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import net.zodac.dicefive.resources.Res
import net.zodac.dicefive.resources.mat_hardwood
import net.zodac.dicefive.resources.mat_marble
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.painterResource

/**
 * A [DiceMat] whose surface is a pre-rendered [texture], cropped to fill the tray - for natural
 * materials that strokes on a Canvas can't make convincing. The textures are generated by
 * `scripts/art/`, not photographs. [palette]'s tray colours are the texture's own average, shown
 * for the moment before it loads.
 */
class TexturedDiceMat(override val id: String, private val texture: DrawableResource, palette: MatPalette) : DiceMat {
    override val diceTrayBrush: Brush = Brush.verticalGradient(listOf(palette.top, palette.bottom))
    override val slotSocketBrush: Brush = Brush.verticalGradient(listOf(palette.slotTop, palette.slotBottom))
    override val slotSocketBorder: Color = palette.slotBorder

    @Composable
    override fun DiceTrayDecoration(modifier: Modifier) {
        Image(painterResource(texture), contentDescription = null, contentScale = ContentScale.Crop, modifier = modifier)
    }
}

/** White marble streaked with charcoal veins; its held-dice slots are sunk into a grey stone. */
val MarbleDiceMat = TexturedDiceMat(
    "marble_white",
    Res.drawable.mat_marble,
    MatPalette(
        top = Color(0xFFEFEEEB),
        bottom = Color(0xFFEBEAE8),
        slotTop = Color(0xFFB4B4B8),
        slotBottom = Color(0xFF9A9A9F),
        slotBorder = Color(0xFFFFFFFF),
        detail = Color(0xFF32323A),
    ),
)

/** Oak floorboards with knots and uneven grooves; its held-dice slots are dark walnut. */
val HardwoodDiceMat = TexturedDiceMat(
    "hardwood",
    Res.drawable.mat_hardwood,
    MatPalette(
        top = Color(0xFF9D6A41),
        bottom = Color(0xFF9C6A41),
        slotTop = Color(0xFF3A2414),
        slotBottom = Color(0xFF24160C),
        slotBorder = Color(0xFFD9A874),
        detail = Color(0xFF3A2414),
    ),
)
